% EEGLAB history file generated on the 13-Nov-2018
% ------------------------------------------------
close all; clear all; clc

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;

sdirs={
 '0028'...
  '0029'...
  '0030'...
  '0031'...
  '0032'...
  '0033'...
  '0036'...
  '0037'...
  '0038'...
  '0040'...
  '0041'...
  '0042'...
  '0043'...
  '0044'...
  '0045'...
  '0046'...
  '0047'...
  '0049'...
  '0050'...
  '0051'...
  '0052'
};


nsubjs = size(sdirs,2)

for i = 1:nsubjs
    EEG = pop_loadset('filename',[sdirs{i} '_events.set'],'filepath',['/Users/e.kubicek/Documents/PEN/ABL/PLDR/DATA/PLDR_H/BV_files/PLDR_' sdirs{i} '/']);
    [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
    EEG = eeg_checkset( EEG );
    EEG = pop_epoch( EEG, {  'GO_S_0'  'GO_S_45'  'GO_S_90'  'HI_S_0'  'HI_S_45'  'HI_S_90'  'JJ_S_0'  'JJ_S_45'  'JJ_S_90'  'JO_S_0'  'JO_S_45'  'JO_S_90'  'JU_S_0'  'JU_S_45'  'JU_S_90'  'UN_S_0'  'UN_S_45'  'UN_S_90'  }, [-1.5           3], 'newname', [sdirs{i} '_epochs'], 'epochinfo', 'yes');
    [ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew',['/Users/e.kubicek/Documents/PEN/ABL/PLDR/DATA/PLDR_H/BV_files/PLDR_' sdirs{i} '/' sdirs{i} '_S_epochs.set'],'gui','off'); 
    EEG = eeg_checkset( EEG );
    EEG = pop_rmbase( EEG, [-1500     0]);
    [ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'overwrite','on','gui','off'); 
    eeglab redraw;
end;

disp(['Finished with ' sdirs{i}])
