% EEGLAB history file generated on the 25-Feb-2018
% ------------------------------------------------
close all; clear all; clc;

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;

sdirs={

'011'...
% '0028' ...
% '0029'...
% '0032'...
% '0033'...
% '035'...
% '0036'...
% '0037'...
% '0038'...
% '0039'...
% '0040'...
% '0041'...
% '0042'...
% '0043'...
% '0046'...
% '0047'...
% '0048'...
% '0049'...
% '0050'

};

nsubjs = size(sdirs,2);

for i = 1:nsubjs, %each subject
    STUDY = []; CURRENTSTUDY = 0; ALLEEG = []; EEG=[]; CURRENTSET=[];
    eeglab/lorna.quandt/Dropbox/ABL/P1/P1_EEG/P1_Datasets/P1_' sdirs{i} '/']);
    [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
    EEG = eeg_checkset( EEG );
    EEG = pop_importevent( EEG, 'append','no','event',['/Users/lorna.quandt/Dropbox/ABL/P1/P1_EEG/P1_Datasets/P1_' sdirs{i} '/' sdirs{i} '_event_import.csv'],'fields',{'latency' 'type'},'timeunit',NaN,'optimalign','off');
    [ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
    EEG = eeg_checkset( EEG );
    EEG = pop_saveset( EEG, 'savemode','resave');
    [ALLEEG EEG] = eeg_store(ALLEEG, EEG, CURRENTSET);
    eeglab redraw;
end; %end of subject loop

disp('Finished');
