% EEGLAB history file generated on the 13-Nov-2018
% ------------------------------------------------
close all; clear all; clc

[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;

sdirs={
 '0003'...
  '0004'...
  '0005'...
  '0007'...
  '0008'...
  '0009'...
  '0011'...
  '0012'...
  '0013'...
  '0014'...
  '0015'...
  '0016'...
  '0020'...
  '0021'...
  '0022'...
  '0023'...
  '0024'...
  '0026'...
  '0027'
};


for i = 1:length(sdirs) %each subject
    EEG = pop_loadset('filename',[sdirs{i} '_events.set'],'filepath',['/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_' sdirs{i} '/']);
    [ALLEEG, EEG, CURRENTSET] = eeg_store( ALLEEG, EEG, 0 );
    EEG = eeg_checkset( EEG );
    EEG = pop_epoch( EEG, {  'JO_U_90'  'HI_U_90'  'UN_U_45'  'GO_U_90' }, [-1.5           3], 'newname', [sdirs{i} '_epochs'], 'epochinfo', 'yes');
    [ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 1,'savenew',['/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_' sdirs{i} '/' sdirs{i} '_hard_epochs.set'],'gui','off'); 
    EEG = eeg_checkset( EEG );
    EEG = pop_rmbase( EEG, [-1500     0]);
    [ALLEEG EEG CURRENTSET] = pop_newset(ALLEEG, EEG, 2,'overwrite','on','gui','off'); 
    eeglab redraw;
end;

disp(['Finished with ' sdirs{i}])
