% EEGLAB history file generated on the 06-Aug-2019
% ------------------------------------------------
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
pop_editoptions( 'option_storedisk', 1, 'option_savetwofiles', 1, 'option_saveversion6', 1, 'option_single', 1, 'option_memmapdata', 0, 'option_eegobject', 0, 'option_computeica', 1, 'option_scaleicarms', 1, 'option_rememberfolder', 1, 'option_donotusetoolboxes', 0, 'option_checkversion', 1, 'option_chat', 0);
[STUDY ALLEEG] = std_editset( STUDY, [], 'name','hard_DvH','task','PLDR','notes','four hard trials only','commands',{...
    {'index' 1 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0003/0003_hard_epochs.set' 'subject' '0003' 'condition' 'hard' 'group' 'deaf'},...
    {'index' 2 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0004/0004_hard_epochs.set' 'subject' '0004' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 3 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0005/0005_hard_epochs.set' 'subject' '0005' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 4 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0007/0007_hard_epochs.set' 'subject' '0007' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 5 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0008/0008_hard_epochs.set' 'subject' '0008' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 6 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0009/0009_hard_epochs.set' 'subject' '0009' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 7 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0011/0011_hard_epochs.set' 'subject' '0011' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 8 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0012/0012_hard_epochs.set' 'subject' '0012' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 9 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0013/0013_hard_epochs.set' 'subject' '0013' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 10 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0014/0014_hard_epochs.set' 'subject' '0014' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 11 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0015/0015_hard_epochs.set' 'subject' '0015' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 12 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0016/0016_hard_epochs.set' 'subject' '0016' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 13 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0020/0020_hard_epochs.set' 'subject' '0020' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 14 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0021/0021_hard_epochs.set' 'subject' '0021' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 15 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0022/0022_hard_epochs.set' 'subject' '0022' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 16 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0023/0023_hard_epochs.set' 'subject' '0023' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 17 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0024/0024_hard_epochs.set' 'subject' '0024' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 18 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0026/0026_hard_epochs.set' 'subject' '0026' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 19 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_D/BV_files/PLDR_0027/0027_hard_epochs.set' 'subject' '0027' 'condition' 'hard' 'group' 'deaf'}...
    {'index' 20 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0028/0028_hard_epochs.set' 'subject' '0028' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 21 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0029/0029_hard_epochs.set' 'subject' '0029' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 22 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0030/0030_hard_epochs.set' 'subject' '0030' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 23 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0031/0031_hard_epochs.set' 'subject' '0031' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 24 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0032/0032_hard_epochs.set' 'subject' '0032' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 25 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0033/0033_hard_epochs.set' 'subject' '0033' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 26 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0036/0036_hard_epochs.set' 'subject' '0036' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 27 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0038/0038_hard_epochs.set' 'subject' '0038' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 28 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0040/0040_hard_epochs.set' 'subject' '0040' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 29 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0041/0041_hard_epochs.set' 'subject' '0041' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 30 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0042/0042_hard_epochs.set' 'subject' '0042' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 31 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0044/0044_hard_epochs.set' 'subject' '0044' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 32 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0045/0045_hard_epochs.set' 'subject' '0045' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 33 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0046/0046_hard_epochs.set' 'subject' '0046' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 34 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0047/0047_hard_epochs.set' 'subject' '0047' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 35 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0049/0049_hard_epochs.set' 'subject' '0049' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 36 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0050/0050_hard_epochs.set' 'subject' '0050' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 37 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0051/0051_hard_epochs.set' 'subject' '0051' 'condition' 'hard' 'group' 'hearing'}...
    {'index' 38 'load' '/Users/lorna.quandt/Dropbox/PLDR/PLDR_data/PLDR_EEGLAB/PLDR_H/BV_files/PLDR_0052/0052_hard_epochs.set' 'subject' '0052' 'condition' 'hard' 'group' 'hearing'}...
    
    },'updatedat','on','savedat','on','rmclust','on' );
[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
eeglab redraw;
